### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cthakar** [beatfreaker/EmojiMatch#1]
Its awesome game so far!! :+1:  One suggestion, if possible than add feature like time/counter so it gets more attentive. also with levels that time/counter become shorter with level increasing.
May be you are also planning for this in next release ! :)

**Comment by beatfreaker** [comment]
@cthakar sure .... will plan for these features in next release :smiley:

**Comment by cthakar** [comment]
:+1: :+1: :+1:
